# Generated by Django 4.0.2 on 2022-02-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testing',
            name='distant',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего задано вопросов'),
        ),
        migrations.AddField(
            model_name='testing',
            name='question',
            field=models.JSONField(default=1, verbose_name='Вопросы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testing',
            name='total',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего вопросов в тесте'),
        ),
    ]
