# Generated by Django 4.0.2 on 2022-02-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testor', '0002_testing_distant_testing_question_alter_testing_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='testing',
            name='diagram',
            field=models.JSONField(default=1, verbose_name='Диаграмма ответов'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='testing',
            name='question',
        ),
        migrations.AddField(
            model_name='testing',
            name='question',
            field=models.ManyToManyField(to='testor.Question', verbose_name='Вопросы'),
        ),
    ]
